name: simport_design_system
description: "simport design system"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get: ^4.7.2
  json_dynamic_widget: ^10.0.1

  flutter_svg: ^2.2.0
  curved_navigation_bar: ^1.0.6
  mix: ^1.7.0
  http: ^1.4.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  flutter_echarts: ^2.5.0
  highcharts_flutter: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39
  table_sticky_headers: ^2.0.5
  dio: ^5.8.0+1
  skeletonizer: ^2.1.0+1
  transformable_list_view: ^0.7.0
  swipe_refresh: ^1.1.2
  introduction_screen: ^3.1.17
  flutter_advanced_drawer: ^1.5.0
  get_storage: ^2.1.1
  heroicons: ^0.11.0
  wave: ^0.2.2
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  mapbox_maps_flutter: ^2.10.0
  expandable_reorderable_list: ^2.0.0
  widgetbook: ^3.15.0
  widgetbook_annotation: ^3.6.0
  flutter_code_editor: ^0.3.4
  device_frame: ^1.4.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  syncfusion_flutter_gauges: ^30.1.42
  cristalyse: ^1.2.0
  graphic: ^2.6.0
  widgets_to_image: ^2.0.1
  graphite: ^1.2.1
  go_router: ^16.2.0
  tab_container: ^3.5.3
  json_editor_flutter: ^1.4.2
  json_explorer: ^0.1.2
  re_editor: ^0.7.0
  flutter_syntax_view: ^4.1.7
  syntax_highlight: ^0.5.0
  flutter_context_menu: ^0.3.0
  flutter_side_menu: ^0.5.41
  badges: ^3.1.2
  sidebarx: ^0.17.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  patterns_canvas: ^0.5.0
  super_context_menu: ^0.9.1
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  provider: ^6.1.5+1

dev_dependencies:
  build_runner: ^2.5.4
  json_dynamic_widget_codegen: ^3.0.0
  widgetbook_generator: ^3.14.0
  graphview: ^1.2.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
